# Generated by Django 4.1.1 on 2022-11-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('movie_id', models.CharField(max_length=50)),
                ('movie_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('vote', models.FloatField(max_length=5)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'API_Comment',
            },
        ),
    ]
